//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cvthequeweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experiences_Professionnelles
    {
        public int Id { get; set; }
        public string Date_Debut { get; set; }
        public string Date_Fin { get; set; }
        public string Nature { get; set; }
        public string tyype { get; set; }
        public string Employeur { get; set; }
        public string Secteur_Activité { get; set; }
        public string Titre_Poste { get; set; }
        public string descriptiion { get; set; }
        public Nullable<int> Duree { get; set; }
        public int Id_Candiat { get; set; }
    
        public virtual Candidat Candidat { get; set; }
    }
}
