//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cvthequeweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Titre { get; set; }
        public string Entreprise { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string typee { get; set; }
        public int Id_Candiat { get; set; }
    
        public virtual Candidat Candidat { get; set; }
    }
}
