namespace Cvthequeweb.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class maj : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Centres_Interet", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.Certifications", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.Competences_Pro", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.Experiences_Pro", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.Formations", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.Langues", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.Poste_Souhaite", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.Projet_Realise", "candidat_Id", "dbo.Candidats");
            DropForeignKey("dbo.References", "candidat_Id", "dbo.Candidats");
            DropIndex("dbo.Centres_Interet", new[] { "candidat_Id" });
            DropIndex("dbo.Certifications", new[] { "candidat_Id" });
            DropIndex("dbo.Competences_Pro", new[] { "candidat_Id" });
            DropIndex("dbo.Experiences_Pro", new[] { "candidat_Id" });
            DropIndex("dbo.Formations", new[] { "candidat_Id" });
            DropIndex("dbo.Langues", new[] { "candidat_Id" });
            DropIndex("dbo.Poste_Souhaite", new[] { "candidat_Id" });
            DropIndex("dbo.Projet_Realise", new[] { "candidat_Id" });
            DropIndex("dbo.References", new[] { "candidat_Id" });
            AddColumn("dbo.Candidats", "CentreInteretId", c => c.String());
            AddColumn("dbo.Candidats", "CertificationId", c => c.String());
            AddColumn("dbo.Candidats", "Competences_Pro", c => c.String());
            AddColumn("dbo.Candidats", "Experiences_Pro", c => c.String());
            AddColumn("dbo.Candidats", "Formations", c => c.String());
            AddColumn("dbo.Candidats", "Langues", c => c.String());
            AddColumn("dbo.Candidats", "Poste_souhaite", c => c.String());
            AddColumn("dbo.Candidats", "Projet_Realise", c => c.String());
            AddColumn("dbo.Candidats", "References", c => c.String());
            AddColumn("dbo.Candidats", "centres_Interet_Id", c => c.Int());
            AddColumn("dbo.Candidats", "certifications_Id", c => c.Int());
            AddColumn("dbo.Candidats", "competences_Pro_Id", c => c.Int());
            AddColumn("dbo.Candidats", "experiences_Pro_Id", c => c.Int());
            AddColumn("dbo.Candidats", "formations_Id", c => c.Int());
            AddColumn("dbo.Candidats", "langues_Id", c => c.Int());
            AddColumn("dbo.Candidats", "poste_souhaite_Id", c => c.Int());
            AddColumn("dbo.Candidats", "projet_realise_Id", c => c.Int());
            AddColumn("dbo.Candidats", "references_Id", c => c.Int());
            CreateIndex("dbo.Candidats", "centres_Interet_Id");
            CreateIndex("dbo.Candidats", "certifications_Id");
            CreateIndex("dbo.Candidats", "competences_Pro_Id");
            CreateIndex("dbo.Candidats", "experiences_Pro_Id");
            CreateIndex("dbo.Candidats", "formations_Id");
            CreateIndex("dbo.Candidats", "langues_Id");
            CreateIndex("dbo.Candidats", "poste_souhaite_Id");
            CreateIndex("dbo.Candidats", "projet_realise_Id");
            CreateIndex("dbo.Candidats", "references_Id");
            AddForeignKey("dbo.Candidats", "centres_Interet_Id", "dbo.Centres_Interet", "Id");
            AddForeignKey("dbo.Candidats", "certifications_Id", "dbo.Certifications", "Id");
            AddForeignKey("dbo.Candidats", "competences_Pro_Id", "dbo.Competences_Pro", "Id");
            AddForeignKey("dbo.Candidats", "experiences_Pro_Id", "dbo.Experiences_Pro", "Id");
            AddForeignKey("dbo.Candidats", "formations_Id", "dbo.Formations", "Id");
            AddForeignKey("dbo.Candidats", "langues_Id", "dbo.Langues", "Id");
            AddForeignKey("dbo.Candidats", "poste_souhaite_Id", "dbo.Poste_Souhaite", "Id");
            AddForeignKey("dbo.Candidats", "projet_realise_Id", "dbo.Projet_Realise", "Id");
            AddForeignKey("dbo.Candidats", "references_Id", "dbo.References", "Id");
            DropColumn("dbo.Centres_Interet", "CandidatId");
            DropColumn("dbo.Centres_Interet", "candidat_Id");
            DropColumn("dbo.Certifications", "CandidatId");
            DropColumn("dbo.Certifications", "candidat_Id");
            DropColumn("dbo.Competences_Pro", "CandidatId");
            DropColumn("dbo.Competences_Pro", "candidat_Id");
            DropColumn("dbo.Experiences_Pro", "CandidatId");
            DropColumn("dbo.Experiences_Pro", "candidat_Id");
            DropColumn("dbo.Formations", "CandidatId");
            DropColumn("dbo.Formations", "candidat_Id");
            DropColumn("dbo.Langues", "CandidatId");
            DropColumn("dbo.Langues", "candidat_Id");
            DropColumn("dbo.Poste_Souhaite", "CandidatId");
            DropColumn("dbo.Poste_Souhaite", "candidat_Id");
            DropColumn("dbo.Projet_Realise", "CandidatId");
            DropColumn("dbo.Projet_Realise", "candidat_Id");
            DropColumn("dbo.References", "CandidatId");
            DropColumn("dbo.References", "candidat_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.References", "candidat_Id", c => c.Int());
            AddColumn("dbo.References", "CandidatId", c => c.String());
            AddColumn("dbo.Projet_Realise", "candidat_Id", c => c.Int());
            AddColumn("dbo.Projet_Realise", "CandidatId", c => c.String());
            AddColumn("dbo.Poste_Souhaite", "candidat_Id", c => c.Int());
            AddColumn("dbo.Poste_Souhaite", "CandidatId", c => c.String());
            AddColumn("dbo.Langues", "candidat_Id", c => c.Int());
            AddColumn("dbo.Langues", "CandidatId", c => c.String());
            AddColumn("dbo.Formations", "candidat_Id", c => c.Int());
            AddColumn("dbo.Formations", "CandidatId", c => c.String());
            AddColumn("dbo.Experiences_Pro", "candidat_Id", c => c.Int());
            AddColumn("dbo.Experiences_Pro", "CandidatId", c => c.String());
            AddColumn("dbo.Competences_Pro", "candidat_Id", c => c.Int());
            AddColumn("dbo.Competences_Pro", "CandidatId", c => c.String());
            AddColumn("dbo.Certifications", "candidat_Id", c => c.Int());
            AddColumn("dbo.Certifications", "CandidatId", c => c.String());
            AddColumn("dbo.Centres_Interet", "candidat_Id", c => c.Int());
            AddColumn("dbo.Centres_Interet", "CandidatId", c => c.String());
            DropForeignKey("dbo.Candidats", "references_Id", "dbo.References");
            DropForeignKey("dbo.Candidats", "projet_realise_Id", "dbo.Projet_Realise");
            DropForeignKey("dbo.Candidats", "poste_souhaite_Id", "dbo.Poste_Souhaite");
            DropForeignKey("dbo.Candidats", "langues_Id", "dbo.Langues");
            DropForeignKey("dbo.Candidats", "formations_Id", "dbo.Formations");
            DropForeignKey("dbo.Candidats", "experiences_Pro_Id", "dbo.Experiences_Pro");
            DropForeignKey("dbo.Candidats", "competences_Pro_Id", "dbo.Competences_Pro");
            DropForeignKey("dbo.Candidats", "certifications_Id", "dbo.Certifications");
            DropForeignKey("dbo.Candidats", "centres_Interet_Id", "dbo.Centres_Interet");
            DropIndex("dbo.Candidats", new[] { "references_Id" });
            DropIndex("dbo.Candidats", new[] { "projet_realise_Id" });
            DropIndex("dbo.Candidats", new[] { "poste_souhaite_Id" });
            DropIndex("dbo.Candidats", new[] { "langues_Id" });
            DropIndex("dbo.Candidats", new[] { "formations_Id" });
            DropIndex("dbo.Candidats", new[] { "experiences_Pro_Id" });
            DropIndex("dbo.Candidats", new[] { "competences_Pro_Id" });
            DropIndex("dbo.Candidats", new[] { "certifications_Id" });
            DropIndex("dbo.Candidats", new[] { "centres_Interet_Id" });
            DropColumn("dbo.Candidats", "references_Id");
            DropColumn("dbo.Candidats", "projet_realise_Id");
            DropColumn("dbo.Candidats", "poste_souhaite_Id");
            DropColumn("dbo.Candidats", "langues_Id");
            DropColumn("dbo.Candidats", "formations_Id");
            DropColumn("dbo.Candidats", "experiences_Pro_Id");
            DropColumn("dbo.Candidats", "competences_Pro_Id");
            DropColumn("dbo.Candidats", "certifications_Id");
            DropColumn("dbo.Candidats", "centres_Interet_Id");
            DropColumn("dbo.Candidats", "References");
            DropColumn("dbo.Candidats", "Projet_Realise");
            DropColumn("dbo.Candidats", "Poste_souhaite");
            DropColumn("dbo.Candidats", "Langues");
            DropColumn("dbo.Candidats", "Formations");
            DropColumn("dbo.Candidats", "Experiences_Pro");
            DropColumn("dbo.Candidats", "Competences_Pro");
            DropColumn("dbo.Candidats", "CertificationId");
            DropColumn("dbo.Candidats", "CentreInteretId");
            CreateIndex("dbo.References", "candidat_Id");
            CreateIndex("dbo.Projet_Realise", "candidat_Id");
            CreateIndex("dbo.Poste_Souhaite", "candidat_Id");
            CreateIndex("dbo.Langues", "candidat_Id");
            CreateIndex("dbo.Formations", "candidat_Id");
            CreateIndex("dbo.Experiences_Pro", "candidat_Id");
            CreateIndex("dbo.Competences_Pro", "candidat_Id");
            CreateIndex("dbo.Certifications", "candidat_Id");
            CreateIndex("dbo.Centres_Interet", "candidat_Id");
            AddForeignKey("dbo.References", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Projet_Realise", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Poste_Souhaite", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Langues", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Formations", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Experiences_Pro", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Competences_Pro", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Certifications", "candidat_Id", "dbo.Candidats", "Id");
            AddForeignKey("dbo.Centres_Interet", "candidat_Id", "dbo.Candidats", "Id");
        }
    }
}
