// <auto-generated />
namespace Cvthequeweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pro_realis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pro_realis));
        
        string IMigrationMetadata.Id
        {
            get { return "201804091010240_pro_realis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
